
name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        ls
        python -m pytest --html=pytest_report.html

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: "Test-Report-Py${{ matrix.python-version }}"
        path: ./*.html

  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python -m PyInstaller "main.py"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: "Pacote-Py${{ matrix.python-version }}"
        path: build/main/main.exe
        
  notification:
      needs: [build, test]

      runs-on: ubuntu-latest
      env:
        EMAIL_ADDRESS: ${{secrets.EMAIL_ADDRESS}}

      steps:
        - name: Executa scripts externos (à fim de enviar e-mail de congratulação!!)
          uses: actions/checkout@v4
        - run: sh scripts/shell.sh
